export const ROUTES = {
  HOME: "/",
  EVENTS: "/events",
  WITH: "/with",
  COMMUNITY: "/community",
  HELP: "/help",
  MYPAGE: "/mypage",
};

export const IMAGES = {
  LOGO: "/img/culture_mate_logo.svg",
  GALLERY_DEFAULT_IMG: "/img/default_img.svg",
};

export const ICONS = {
  SEARCH: "/img/search.svg",
  DEFAULT_PROFILE: "/img/profile.svg",
  LOGOUT_BTN: "/img/logout.svg",
  HEART: "/img/heart.svg",
  HEART_EMPTY: "/img/heart-empty.svg",
  FIRE: "/img/fire.svg",
  FILTER: "/img/filter.svg",
  EDIT_GRAY: "/img/edit_gray.svg",
  FACEBOOK: "/img/facebook.svg",
  KAKAOTALK: "/img/kakaotalk.svg",
  INSTAGRAM: "/img/instagram.svg",
  YOUTUBE: "/img/youtube.svg",
  EDIT: "/img/edit.svg",
  EDIT_GRAY: "/img/edit_gray.svg",
  X: "/img/x.svg",
  ADD_GRAY: "/img/add_gray.svg",
  DOWN_GRAY: "/img/down_gray.svg",
  RIGHT_GRAY: "/img/right_gray.svg",
  VISIBLE: "/img/visible.svg",
  INVISIBLE: "/img/invisible.svg",
  CALENDAR: "/img/calendar.svg",
  GROUP: "/img/group.svg",
  PIN: "/img/pin.svg",
  DOWN_ARROW: "/img/down_arrow.svg",
  VIEWTYPE_LIST: "/img/list.svg",
  VIEWTYPE_GALLERY: "/img/menu.svg",
  DELETE: "/img/delete.svg",
  REPLY: "/img/curved_arrow.svg",
  TOGGLE_ON: "/img/toggle_on.svg",
  TOGGLE_OFF: "/img/toggle_off.svg",
  SETTING: "/img/setting.svg",
};