export const ROUTES = {
  HOME: "/",
  EVENTS: "/events",
  WITH: "/with",
  COMMUNITY: "/community",
  HELP: "/help",
  MYPAGE: "/mypage",
  FACEBOOK: "https://facebook.com/yourpage",
  INSTAGRAM: "https://instagram.com/yourpage",
  YOUTUBE: "https://youtube.com/yourpage",
  KAKAOTALK: "https://open.kakao.com/yourpage",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  LOCATION_TERMS: "/location",
  YOUTH_PROTECTION: "/youth",
  EMAIL_POLICY: "/email-policy",
  ABOUT: "/about",
  GUIDE: "/guide",
  NOTICE: "/notice",
  FAQ: "/faq",
  CONTACT: "/contact",
};

export const IMAGES = {
  LOGO: "/img/culture_mate_logo.svg",
  GALLERY_DEFAULT_IMG: "/img/default_img.svg",
};

export const ICONS = {
  SEARCH: "/img/search.svg",
  DEFAULT_PROFILE: "/img/profile.svg",
  LOGOUT_BTN: "/img/logout.svg",
  HEART: "/img/heart.svg",
  HEART_EMPTY: "/img/heart-empty.svg",
  FIRE: "/img/fire.svg",
  FILTER: "/img/filter.svg",
  EDIT_GRAY: "/img/edit_gray.svg",
  FACEBOOK: "/img/facebook.svg",
  KAKAOTALK: "/img/kakaotalk.svg",
  INSTAGRAM: "/img/instagram.svg",
  YOUTUBE: "/img/youtube.svg",
  EDIT: "/img/edit.svg",
  X: "/img/x.svg",
  ADD_GRAY: "/img/add_gray.svg",
  DOWN_GRAY: "/img/down_gray.svg",
  RIGHT_GRAY: "/img/right_gray.svg",
  VISIBLE: "/img/visible.svg",
  INVISIBLE: "/img/invisible.svg",
  CALENDAR: "/img/calendar.svg",
  GROUP: "/img/group.svg",
  PIN: "/img/pin.svg",
  STAR_EMPTY: "/img/star_empty.svg",
  STAR_FULL: "/img/star_full.svg",
  STAR_HALF: "/img/star_half.svg",
  UP_ARROW: "/img/up_arrow.svg",
  DOWN_ARROW: "/img/down_arrow.svg",
  LEFT_ARROW: "/img/left_arrow.svg",
  RIGHT_ARROW: "/img/right_arrow.svg",
  VIEWTYPE_LIST: "/img/list.svg",
  VIEWTYPE_GALLERY: "/img/menu.svg",
};
