/**목업데이터 (단순 배열이라 js사용) */
// 서버 없이 SearchToWrite(mockData)로 테스트할 때 사용하는 로컬 목업
const mockEvents = [
  {
    id: 1,
    name: '서울 재즈 페스티벌',
    eventType: '음악',
    image: '/img/jazz-festival.jpeg',
    description: '서울 최대 규모의 재즈 페스티벌',
    rating: 4.5,
    likes: 156,
    postsCount: 42,
    isLiked: false,
  },
  {
    id: 2,
    name: '부산 국제 영화제',
    eventType: '문화',
    image: '/img/busan-film-festival.jpeg',
    description: '아시아 최대 국제 영화제',
    rating: 4.8,
    likes: 289,
    postsCount: 78,
    isLiked: false,
  },
  {
    id: 3,
    name: '강남 클래식 콘서트',
    eventType: '음악',
    image: '/img/classic-concert.jpeg',
    description: '베토벤 교향곡 전곡 연주',
    rating: 4.6,
    likes: 127,
    postsCount: 34,
    isLiked: true,
  },

  {
    id: 4,
    name: '고흐 몰입형 전시',
    eventType: '전시',
    image: '/img/vangoh.jpeg',
    description:
      '빈센트 반 고흐의 작품을 디지털 아트로 재해석한 몰입형 미디어 전시',
    rating: 4.7,
    likes: 1234,
    postsCount: 345,
    isLiked: true,
  },
  {
    id: 5,
    name: '라이온킹 뮤지컬',
    eventType: '뮤지컬',
    image: '/img/lionking.jpeg',
    description: '브로드웨이 원작 디즈니의 대표 뮤지컬 라이온킹 한국 공연',
    rating: 4.9,
    likes: 2156,
    postsCount: 567,
    isLiked: false,
  },
  {
    id: 6,
    name: 'BTS 월드투어 콘서트',
    eventType: '콘서트',
    image: '/img/bts.jpeg',
    description: '방탄소년단의 글로벌 월드투어 서울 스페셜 콘서트',
    rating: 4.8,
    likes: 5432,
    postsCount: 1234,
    isLiked: true,
  },
  {
    id: 7,
    name: '현대미술관 피카소 특별전',
    eventType: '전시',
    image: '/img/picasso.jpeg',
    description:
      '파블로 피카소의 청색 시대부터 입체파까지 대표작 100여 점 전시',
    rating: 4.5,
    likes: 876,
    postsCount: 189,
    isLiked: false,
  },
  {
    id: 8,
    name: '오페라의 유령',
    eventType: '뮤지컬',
    image: '/img/phantom.jpeg',
    description: '앤드류 로이드 웨버의 불멸의 걸작 오페라의 유령 내한 공연',
    rating: 4.6,
    likes: 1567,
    postsCount: 423,
    isLiked: true,
  },
  {
    id: 9,
    name: '아이유 콘서트 골든아워',
    eventType: '콘서트',
    image: '/img/iu.jpeg',
    description: '아이유의 신곡과 히트곡을 만날 수 있는 단독 콘서트',
    rating: 4.8,
    likes: 3421,
    postsCount: 789,
    isLiked: false,
  },
  {
    id: 10,
    name: '팀랩 보더리스 서울',
    eventType: '전시',
    image: '/img/timlab.jpeg',
    description: '일본 팀랩의 디지털 아트 전시 한국 최초 상설 전시관',
    rating: 4.4,
    likes: 2345,
    postsCount: 678,
    isLiked: true,
  },
  {
    id: 11,
    name: '레미제라블',
    eventType: '뮤지컬',
    image: '/img/lesMiserable.jpeg',
    description: '빅토르 위고 원작의 감동적인 뮤지컬 레미제라블 한국어 버전',
    rating: 4.7,
    likes: 1234,
    postsCount: 234,
    isLiked: false,
  },
  {
    id: 12,
    name: '콜드플레이 내한 콘서트',
    eventType: '콘서트',
    image: '/img/coldplay.jpeg',
    description: '영국 록밴드 콜드플레이의 7년 만의 한국 단독 콘서트',
    rating: 4.9,
    likes: 4567,
    postsCount: 1012,
    isLiked: true,
  },
  {
    id: 13,
    name: '아이키 콘서트',
    eventType: '콘서트',
    image: '/img/i-key.jpeg',
    description: '스트리트 우먼 파이터 아이키의 콘서트',
    rating: 4.0,
    likes: 3822,
    postsCount: 1342,
    isLiked: true,
  },
  {
    id: 14,
    name: '아이들 콘서트',
    eventType: '콘서트',
    image: '/img/idle.jpeg',
    description: '여자아이들의 단독 콘서트',
    rating: 4.3,
    likes: 14567,
    postsCount: 2112,
    isLiked: false,
  },
  {
    id: 15,
    name: '아이브 콘서트',
    eventType: '콘서트',
    image: '/img/ive.jpeg',
    description: '아이브 첫 단독 콘서트',
    rating: 5,
    likes: 14567,
    postsCount: 3012,
    isLiked: true,
  },
  {
    id: 16,
    name: '날씨의 아이 필름 콘서트',
    eventType: '콘서트',
    image: '/img/weather-i.jpeg',
    description: '애니메이션 날씨의 아이 필름 콘서트',
    rating: 2,
    likes: 5526,
    postsCount: 2312,
    isLiked: true,
  },
  {
    id: 17,
    name: '최애의 아이 전시회',
    eventType: '전시',
    image: '/img/ani-i.jpeg',
    description: 'TV 애니메이션 【최애의 아이】展 거짓말과 아이／빛과 그림자',
    rating: 4.9,
    likes: 4567,
    postsCount: 1012,
    isLiked: false,
  },
  {
    id: 18,
    name: '위아이 콘서트',
    eventType: '콘서트',
    image: '/img/wei.jpeg',
    description: '5인조 아이돌 그룹 위아이의 단독 콘서트',
    rating: 1,
    likes: 4567,
    postsCount: 1012,
    isLiked: true,
  },
  {
    id: 19,
    name: '불켜는 아이',
    eventType: '연극',
    image: '/img/fire-i.jpeg',
    description: '어린이날을 약속한 소파 방정환의 삶과 의미를 그린 작품',
    rating: 4,
    likes: 567,
    postsCount: 812,
    isLiked: false,
  },
  {
    id: 20,
    name: '아이조아 여름축제',
    eventType: '지역 행사',
    image: '/img/i-zoa.jpeg',
    description: '우리 아이들이 신나는 하루 아이조아 장수읍 여름축제',
    rating: 3,
    likes: 567,
    postsCount: 812,
    isLiked: true,
  },
];

export default mockEvents;
