import InterestTab from "@/components/mypage/InterestTab";
import PageTitle from "@/components/global/PageTitle";
import { useMemo } from "react";

export default function Interest() {
  const eventData = useMemo(
    () => [
      {
        imgSrc: "",
        alt: "",
        title: "제목-1",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-2",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-3",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-4",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-5",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-6",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-7",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-8",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-9",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-1",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-2",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-3",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-4",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-5",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-6",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-7",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-8",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-9",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-1",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-2",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-3",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-4",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-5",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-6",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-7",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-8",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: true,
      },
      {
        imgSrc: "",
        alt: "",
        title: "제목-9",
        date: "0000.00.00 ~ 0000.00.00",
        location: "지역 및 장소명",
        isHot: false,
      },
    ],
    []
  );
  return (
    <>
      <PageTitle>관심 목록</PageTitle>
      <div className="mt-4 space-y-1">
        <InterestTab eventData={eventData} />
      </div>
    </>
  );
}
