import LoginProvider from '@/components/auth/LoginProvider';
import NavigationBar from '@/components/global/NavigationBar';
import Footer from '@/components/global/Footer';
import './globals.css';

export const metadata = {
  title: '컬쳐메이트 - CultureM8',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <LoginProvider>
          <NavigationBar />
          {children}
          <Footer />
        </LoginProvider>
      </body>
    </html>
  );
}
