import NavigationBar from "@/components/global/NavigationBar";
import "./globals.css";

export const metadata = {
  title: "컬쳐메이트 - CultureM8",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <NavigationBar />
        <main className="mx-auto max-w-300 px-[clamp(0px,6vw,0px)] relative">
          {children}
        </main>
      </body>
    </html>
  );
}
